//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBusStation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusTicketDBEntities1 : DbContext
    {
        private static BusTicketDBEntities1 _context;
        public static BusTicketDBEntities1 GetContext()
        {
            if (_context == null)
                _context = new BusTicketDBEntities1();
            return _context;
        }
        public BusTicketDBEntities1()
            : base("name=BusTicketDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Buses> Buses { get; set; }
        public DbSet<Passangers> Passangers { get; set; }
        public DbSet<Payments> Payments { get; set; }
        public DbSet<Routes> Routes { get; set; }
        public DbSet<Schedules> Schedules { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tickets> Tickets { get; set; }
    }
}
