//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBusStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public Schedules()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public int RouteID { get; set; }
        public System.DateTime DepartureData { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public int BusId { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
